export const SET_LOGIN = 'SET_LOGIN'
export const SET_PROFILE = 'SET_PROFILE'


export const SET_NEWS_INDEX = 'SET_NEWS_INDEX'
export const SET_NEWS_READY = 'SET_NEWS_READY'
export const SET_NEWS = 'SET_NEWS'

export const SET_SIGN_UP_FORM = 'SET_SIGN_UP_FORM'
export const SET_LOGIN_ERROR_MSG = 'SET_LOGIN_ERROR_MSG'
export const ON_LOGIN ='ON_LOGIN'
export const ON_SIGN_UP = 'ON_SIGN_UP'
export const SET_SIGN_UP_ERROR_MSG = 'SET_SIGN_UP_ERROR_MSG'

export const SET_POSTS = 'SET_POSTS'
export const SET_POSTS_READY = 'POSTS_READY'
export const SHOW_CREATE_POST = 'SHOW_CREATE_POST'
export const SET_SEARCH_USER = 'SET_SEARCH_USER'
export const SHOW_SEARCH_USER = 'SHOW_SEARCH_USER'
export const SET_FOLLOW_ERROR_MSG = 'SET_FOLLOW_ERROR_MSG'